default:
  tags:
    - docker
    - typescript

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in every branch.
  stage: build
  image: node:22-alpine3.19
  artifacts: # TODO: Lookup
    untracked: true
  script:
    - npm i

ui-test-job:   # This job runs only on main and develop branch.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: node:22-alpine3.19
  only:
    - main
    - develop
  before_script:
    - npm i
  script:
    - npm run test:ci
  coverage:  /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always # TODO: Lookup
    reports:
      junit:
        - junit.xml
